// packages/react-template/src/pages/TestCom/Testcom.tsx
/*
 * @Description: 
 * @Version: 2.0
 * @Autor: liushuhao
 * @Date: 2022-01-12 16:34:52
 * @LastEditors: liushuhao
 * @LastEditTime: 2022-01-12 16:43:30
 */
// import "./Home.less";
import React, { FC } from "react";
import Swiper from '@components/Gallery/Gallery';
const Home: FC<{}> = () => {
  return (
    <>
      <div className='page-home layout-container'>
        <div className='banner-box'>
            <span>1111</span>
            {/* 轮播组件 swiper */}
            {/* <Swiper /> */}
        </div>
      </div>
    </>
  );
};
export default Home;

// packages/webpack_test/src/views/testCom.vue
<!--
 * @Description: vue
 * @Version: 2.0
 * @Autor: liushuhao
 * @Date: 2021-11-15 11:01:05
 * @LastEditors: liushuhao
 * @LastEditTime: 2021-11-15 16:32:45
-->
<template>
    <div class="index">
        <span>dddd</span>
    </div>
</template>

<script lang="ts">
import { ref, defineComponent } from 'vue'

export default defineComponent({
    setup() {
        const test = '111'
        return {}
    }
})
</script>

<style scoped lang="less"></style>
